"""
build.py
--------
Concatenates all local JS modules (in load order from index.html) into
static/js/bundle.js.

Run manually:   python build.py
Auto-run:       called from app.py startup when any source file is newer than bundle.

Vendor files (static/js/vendor/*.js) are NOT bundled — they're already local
and loaded separately so the browser can cache them independently.
"""
import os
import re
import sys

BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
INDEX_HTML = os.path.join(BASE_DIR, 'templates', 'index.html')
BUNDLE_OUT = os.path.join(BASE_DIR, 'static', 'js', 'bundle.js')


def get_local_script_paths():
    """Parse index.html and return ordered list of local (non-vendor) JS file paths."""
    with open(INDEX_HTML, encoding='utf-8') as f:
        html = f.read()
    # Match all local /static/js/ scripts that are NOT vendor and NOT bundle itself
    matches = re.findall(r'<script[^>]+src="(/static/js/(?!vendor)(?!bundle)[^"?]+)', html)
    paths = []
    for src in matches:
        # Convert URL path to filesystem path
        fpath = os.path.join(BASE_DIR, src.lstrip('/').replace('/', os.sep))
        if os.path.isfile(fpath):
            paths.append((src, fpath))
        else:
            print(f'  [build] WARNING: not found: {fpath}', file=sys.stderr)
    return paths


def needs_rebuild(source_paths):
    """Return True if bundle.js doesn't exist or any source is newer than bundle."""
    if not os.path.exists(BUNDLE_OUT):
        return True
    bundle_mtime = os.path.getmtime(BUNDLE_OUT)
    # Also check index.html itself (script order could have changed)
    if os.path.getmtime(INDEX_HTML) > bundle_mtime:
        return True
    for _, fpath in source_paths:
        if os.path.getmtime(fpath) > bundle_mtime:
            return True
    return False


def build(force=False):
    """Build bundle.js. Returns True if bundle was (re)built."""
    paths = get_local_script_paths()
    if not paths:
        print('[build] No local scripts found in index.html', file=sys.stderr)
        return False

    if not force and not needs_rebuild(paths):
        return False  # already up to date

    parts = [
        '/* Trading Journal — JS bundle (auto-generated by build.py) */',
        '/* Do NOT edit this file directly — edit the source modules  */',
        '',
    ]
    total_bytes = 0
    for src, fpath in paths:
        with open(fpath, encoding='utf-8') as f:
            content = f.read()
        parts.append(f'\n/* ── {src} ── */')
        parts.append(content)
        total_bytes += len(content.encode('utf-8'))

    bundle_content = '\n'.join(parts)
    with open(BUNDLE_OUT, 'w', encoding='utf-8') as f:
        f.write(bundle_content)

    print(f'[build] bundle.js: {len(paths)} files -> {total_bytes / 1024:.0f} KB '
          f'({os.path.getsize(BUNDLE_OUT) / 1024:.0f} KB on disk)')
    return True


if __name__ == '__main__':
    force = '--force' in sys.argv
    rebuilt = build(force=force)
    if not rebuilt:
        print('[build] bundle.js is up to date — use --force to rebuild')
